// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG-vjA476JsBEY7aSpiGoU09aqhg98bp4',
    appId: '1:145422957663:web:8805da674c50a80985afea',
    messagingSenderId: '145422957663',
    projectId: 'gym-buddy-v2',
    authDomain: 'gym-buddy-v2.firebaseapp.com',
    storageBucket: 'gym-buddy-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8gyWqq0CDjjD577-80B0eijWJGsC4ea8',
    appId: '1:145422957663:ios:82f7f6048f16626d85afea',
    messagingSenderId: '145422957663',
    projectId: 'gym-buddy-v2',
    storageBucket: 'gym-buddy-v2.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8gyWqq0CDjjD577-80B0eijWJGsC4ea8',
    appId: '1:145422957663:ios:82f7f6048f16626d85afea',
    messagingSenderId: '145422957663',
    projectId: 'gym-buddy-v2',
    storageBucket: 'gym-buddy-v2.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp1',
  );
}
